apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-canary
  namespace: myapp-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: myapp
      role: frontend
      version: canary
  template:
    metadata:
      labels:
        app: myapp
        role: frontend
        version: canary
    spec:
      containers:
        - name: myapp
          image: public.ecr.aws/docker/library/nginx:1.27-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html
              name: version
              subPath: index.html
      volumes:
        - name: version
          configMap:
            name: version-html-canary    
