# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
- path: patch-image-stable.yaml
- path: patch-image-canary.yaml
- path: patch-canary-weight.yaml
  # - promote-switch-active.yaml   # include when you want to cut over
