# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch-image-stable.yaml
  - patch-image-canary.yaml
  - patch-canary-weight.yaml
  # - promote-switch-active.yaml   # include when you want to cut over
