apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-stable
  namespace: myapp-dev
spec:
  template:
    spec:
      containers:
        - name: myapp
          image: public.ecr.aws/docker/library/nginx:1.26-alpine
          imagePullPolicy: IfNotPresent
