apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/bindumva/gitops-canary-nginx.git
  destinations:
    - namespace: myapp-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
